# CORRECTED Fongbe wav2vec-U 2.0 Training Configuration
# Aligned with the paper "Towards End-to-end Unsupervised Speech Recognition"

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: /workspace/fongbe_tensorboard_official

checkpoint:
  save_interval_updates: 1000
  keep_last_epochs: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: ucv_metric # Use the Unsupervised Cross-Validation Metric

distributed_training:
  distributed_world_size: 1

task:
  _name: unsupervised_speech_recognition
  data: ??? # Overridden by your shell script
  text_data: ??? # Overridden by your shell script
  pseudo_label_key: km # Tells the task to look for .km files

criterion:
  _name: unsupervised_criterion
  # Loss weights from Section 4.1 of the paper
  lambda_gp: 1.5
  gamma_sp: 1.5
  eta_pd: 0.3
  delta_sl: 0.5 # The new auxiliary self-supervised loss

optimization:
  max_update: 100000 # Use the value from your script's override
  update_freq: [1]

optimizer:
  _name: composite
  groups:
    generator:
      optimizer:
        _name: adam
        adam_betas: [0.8, 0.9]
        lr: [0.00005]
      lr_scheduler:
        _name: fixed
    discriminator:
      optimizer:
        _name: adam
        adam_betas: [0.8, 0.9]
        lr: [0.0003]
      lr_scheduler:
        _name: fixed

lr_scheduler: pass_through

model:
  _name: wav2vec_u2

  # --- Generator Configuration ---
  extractor_mode: default
  encoder_embed_dim: 1024
  encoder_conv_stride: [3] # Replaces manual pooling
  encoder_conv_kernel: [5]
  batch_norm_scale: 35.0 # Replaces PCA, 35 is for XLSR-53

  # --- Discriminator Configuration ---
  discriminator_depth: 2
  discriminator_kernel: 3
  discriminator_dim: 256
  discriminator_in_dim: 256
  discriminator_dropout: 0.1
  discriminator_grad_mult: 1.0

dataset:
  train_subset: train
  valid_subset: valid
  num_workers: 6
  max_tokens: 1400000
  batch_size: 160 # Use the value from your script's override
  validate_interval: 5
  validate_interval_updates: 1000 # Use the value from your script's override
  skip_invalid_size_inputs_valid_test: true